### ISSUE TITLE
Erreurs sur certains themes

### ISSUE THREAD

**Issue by chikamichi** [nono/slide-em-up#1]
- Il manque le dossier themes/default.
- Quand on utilise le thème "common", on a cette erreur en rendu :
  
  ```
  [:error, "No such file or directory - /home/jd/.rvm/gems/ruby-1.9.2-p290@global/gems/slide-em-up-0.1.8/themes/common/index.erb"]
  ```

**Comment by nono** [comment]
Le theme `default` n'a jamais existé. Je comptais en créer un, mais pas le temps. Par défaut, ce sera le thème shower.

Et common n'est pas un terme mais juste un répertoire pour des ressources communes à plusieurs thèmes.
